language: csharp

sudo: false  # use the new container-based Travis infrastructure

before_script:
 - chmod +x ./build.sh

script: 
  - ./build.sh RunTests "Version=0.1.$TRAVIS_BUILD_NUMBER"
  - "[ $TRAVIS_PULL_REQUEST = 'false' ] && [ $TRAVIS_BRANCH = 'publish' ] && ./build.sh Publish"
